- name: Install Mysql
  hosts: db
  become: yes
  vars:
    new_mysql_root_password: redacted
    mysqlsoftware:
      - mysql-server
      - mysql-client
  tasks:
    - name: "apt-get update"
      apt:
        update-cache: yes
        cache_valid_time: 300
    - name: "install mysql SERVER"
      shell: apt-get -y install mysql-server
    - name: "install mysql CLIENT"
      shell: apt-get -y install mysql-client
    - name: "install phpmyadmin"
      shell: apt-get -y install phpmyadmin
    - name: "Start MYSQL service"
      action: service name=mysql state=started
-name: Install SpringBoot API
  hosts: web
  become: yes
  tasks:
    - name: "apt-get update"
      apt:
        update-cache: yes
        cache_valid_time: 300
    - name: "install java"
      shell: apt-get -y install java
